led_action_server:
  ros__parameters:
    led_count: 60
    backend: "simulate"
    pixel_order: "BRG"
    default_brightness: 0.4
    action_name: "led_pattern"
    cancel_service_name: "cancel_led_pattern"
    frame_rate: 40.0
